/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoomRouteImport } from './routes/room'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as XCardTestRouteImport } from './routes/x-card-test'
import { Route as XCardTest2RouteImport } from './routes/x-card-test-2'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AmbassadorsIndexRouteImport } from './routes/ambassadors.index'
import { Route as AmbassadorsIdRouteImport } from './routes/ambassadors.$id'
import { Route as BuildersIndexRouteImport } from './routes/builders.index'
import { Route as BuildersIdRouteImport } from './routes/builders.$id'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as KrewIdIndexRouteImport } from './routes/krew-id/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as ProfileCardRouteImport } from './routes/profile.card'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as VenuesIndexRouteImport } from './routes/venues.index'
import { Route as VenuesSlugRouteImport } from './routes/venues.$slug'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminOpportunitiesNewRouteImport } from './routes/admin.opportunities.new'
import { Route as KrewIdManageTokenRouteImport } from './routes/krew-id/manage.$token'
import { Route as AdminEventsIdEditRouteImport } from './routes/admin.events.$id.edit'
import { Route as AdminOpportunitiesIdEditRouteImport } from './routes/admin.opportunities.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const XCardTestRoute = XCardTestRouteImport.update({
  id: '/x-card-test',
  path: '/x-card-test',
  getParentRoute: () => rootRouteImport,
} as any)
const XCardTest2Route = XCardTest2RouteImport.update({
  id: '/x-card-test-2',
  path: '/x-card-test-2',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsIndexRoute = AmbassadorsIndexRouteImport.update({
  id: '/ambassadors/',
  path: '/ambassadors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsIdRoute = AmbassadorsIdRouteImport.update({
  id: '/ambassadors/$id',
  path: '/ambassadors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIndexRoute = BuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIdRoute = BuildersIdRouteImport.update({
  id: '/builders/$id',
  path: '/builders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KrewIdIndexRoute = KrewIdIndexRouteImport.update({
  id: '/krew-id/',
  path: '/krew-id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileCardRoute = ProfileCardRouteImport.update({
  id: '/profile/card',
  path: '/profile/card',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesIndexRoute = VenuesIndexRouteImport.update({
  id: '/venues/',
  path: '/venues/',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesSlugRoute = VenuesSlugRouteImport.update({
  id: '/venues/$slug',
  path: '/venues/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminOpportunitiesNewRoute = AdminOpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOpportunitiesRoute,
} as any)
const KrewIdManageTokenRoute = KrewIdManageTokenRouteImport.update({
  id: '/krew-id/manage/$token',
  path: '/krew-id/manage/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIdEditRoute = AdminEventsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminOpportunitiesIdEditRoute =
  AdminOpportunitiesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminOpportunitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/x-card-test': typeof XCardTestRoute
  '/x-card-test-2': typeof XCardTest2Route
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/card': typeof ProfileCardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ambassadors/': typeof AmbassadorsIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/krew-id/': typeof KrewIdIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/krew-id/manage/$token': typeof KrewIdManageTokenRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/x-card-test': typeof XCardTestRoute
  '/x-card-test-2': typeof XCardTest2Route
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/card': typeof ProfileCardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/ambassadors': typeof AmbassadorsIndexRoute
  '/builders': typeof BuildersIndexRoute
  '/events': typeof EventsIndexRoute
  '/krew-id': typeof KrewIdIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/venues': typeof VenuesIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/krew-id/manage/$token': typeof KrewIdManageTokenRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/signup': typeof SignupRoute
  '/submit': typeof SubmitRoute
  '/x-card-test': typeof XCardTestRoute
  '/x-card-test-2': typeof XCardTest2Route
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/events/$id': typeof EventsIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/profile/card': typeof ProfileCardRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/venues/$slug': typeof VenuesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/ambassadors/': typeof AmbassadorsIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/krew-id/': typeof KrewIdIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/venues/': typeof VenuesIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/krew-id/manage/$token': typeof KrewIdManageTokenRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/about'
    | '/contact'
    | '/guidelines'
    | '/login'
    | '/room'
    | '/saved'
    | '/signup'
    | '/submit'
    | '/x-card-test'
    | '/x-card-test-2'
    | '/admin/events'
    | '/admin/login'
    | '/admin/members'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/events/$id'
    | '/opportunities/$id'
    | '/profile/card'
    | '/projects/$id'
    | '/venues/$slug'
    | '/admin/'
    | '/ambassadors/'
    | '/builders/'
    | '/events/'
    | '/krew-id/'
    | '/opportunities/'
    | '/profile/'
    | '/projects/'
    | '/venues/'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/krew-id/manage/$token'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/about'
    | '/contact'
    | '/guidelines'
    | '/login'
    | '/room'
    | '/saved'
    | '/signup'
    | '/submit'
    | '/x-card-test'
    | '/x-card-test-2'
    | '/admin/events'
    | '/admin/login'
    | '/admin/members'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/events/$id'
    | '/opportunities/$id'
    | '/profile/card'
    | '/projects/$id'
    | '/venues/$slug'
    | '/admin'
    | '/ambassadors'
    | '/builders'
    | '/events'
    | '/krew-id'
    | '/opportunities'
    | '/profile'
    | '/projects'
    | '/venues'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/krew-id/manage/$token'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/about'
    | '/contact'
    | '/guidelines'
    | '/login'
    | '/room'
    | '/saved'
    | '/signup'
    | '/submit'
    | '/x-card-test'
    | '/x-card-test-2'
    | '/admin/events'
    | '/admin/login'
    | '/admin/members'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/events/$id'
    | '/opportunities/$id'
    | '/profile/card'
    | '/projects/$id'
    | '/venues/$slug'
    | '/admin/'
    | '/ambassadors/'
    | '/builders/'
    | '/events/'
    | '/krew-id/'
    | '/opportunities/'
    | '/profile/'
    | '/projects/'
    | '/venues/'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/krew-id/manage/$token'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GuidelinesRoute: typeof GuidelinesRoute
  LoginRoute: typeof LoginRoute
  RoomRoute: typeof RoomRoute
  SavedRoute: typeof SavedRoute
  SignupRoute: typeof SignupRoute
  SubmitRoute: typeof SubmitRoute
  XCardTestRoute: typeof XCardTestRoute
  XCardTest2Route: typeof XCardTest2Route
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRouteWithChildren
  AmbassadorsIdRoute: typeof AmbassadorsIdRoute
  BuildersIdRoute: typeof BuildersIdRoute
  EventsIdRoute: typeof EventsIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ProfileCardRoute: typeof ProfileCardRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  VenuesSlugRoute: typeof VenuesSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AmbassadorsIndexRoute: typeof AmbassadorsIndexRoute
  BuildersIndexRoute: typeof BuildersIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  KrewIdIndexRoute: typeof KrewIdIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  VenuesIndexRoute: typeof VenuesIndexRoute
  KrewIdManageTokenRoute: typeof KrewIdManageTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x-card-test': {
      id: '/x-card-test'
      path: '/x-card-test'
      fullPath: '/x-card-test'
      preLoaderRoute: typeof XCardTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/x-card-test-2': {
      id: '/x-card-test-2'
      path: '/x-card-test-2'
      fullPath: '/x-card-test-2'
      preLoaderRoute: typeof XCardTest2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors/': {
      id: '/ambassadors/'
      path: '/ambassadors'
      fullPath: '/ambassadors/'
      preLoaderRoute: typeof AmbassadorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors/$id': {
      id: '/ambassadors/$id'
      path: '/ambassadors/$id'
      fullPath: '/ambassadors/$id'
      preLoaderRoute: typeof AmbassadorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/': {
      id: '/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof BuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/$id': {
      id: '/builders/$id'
      path: '/builders/$id'
      fullPath: '/builders/$id'
      preLoaderRoute: typeof BuildersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/krew-id/': {
      id: '/krew-id/'
      path: '/krew-id'
      fullPath: '/krew-id/'
      preLoaderRoute: typeof KrewIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/card': {
      id: '/profile/card'
      path: '/profile/card'
      fullPath: '/profile/card'
      preLoaderRoute: typeof ProfileCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/': {
      id: '/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof VenuesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues/$slug': {
      id: '/venues/$slug'
      path: '/venues/$slug'
      fullPath: '/venues/$slug'
      preLoaderRoute: typeof VenuesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/opportunities/new': {
      id: '/admin/opportunities/new'
      path: '/new'
      fullPath: '/admin/opportunities/new'
      preLoaderRoute: typeof AdminOpportunitiesNewRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/krew-id/manage/$token': {
      id: '/krew-id/manage/$token'
      path: '/krew-id/manage/$token'
      fullPath: '/krew-id/manage/$token'
      preLoaderRoute: typeof KrewIdManageTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$id/edit': {
      id: '/admin/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/opportunities/$id/edit': {
      id: '/admin/opportunities/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/opportunities/$id/edit'
      preLoaderRoute: typeof AdminOpportunitiesIdEditRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIdEditRoute: typeof AdminEventsIdEditRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIdEditRoute: AdminEventsIdEditRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminOpportunitiesRouteChildren {
  AdminOpportunitiesNewRoute: typeof AdminOpportunitiesNewRoute
  AdminOpportunitiesIdEditRoute: typeof AdminOpportunitiesIdEditRoute
}

const AdminOpportunitiesRouteChildren: AdminOpportunitiesRouteChildren = {
  AdminOpportunitiesNewRoute: AdminOpportunitiesNewRoute,
  AdminOpportunitiesIdEditRoute: AdminOpportunitiesIdEditRoute,
}

const AdminOpportunitiesRouteWithChildren =
  AdminOpportunitiesRoute._addFileChildren(AdminOpportunitiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GuidelinesRoute: GuidelinesRoute,
  LoginRoute: LoginRoute,
  RoomRoute: RoomRoute,
  SavedRoute: SavedRoute,
  SignupRoute: SignupRoute,
  SubmitRoute: SubmitRoute,
  XCardTestRoute: XCardTestRoute,
  XCardTest2Route: XCardTest2Route,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRouteWithChildren,
  AmbassadorsIdRoute: AmbassadorsIdRoute,
  BuildersIdRoute: BuildersIdRoute,
  EventsIdRoute: EventsIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ProfileCardRoute: ProfileCardRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  VenuesSlugRoute: VenuesSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  AmbassadorsIndexRoute: AmbassadorsIndexRoute,
  BuildersIndexRoute: BuildersIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  KrewIdIndexRoute: KrewIdIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  VenuesIndexRoute: VenuesIndexRoute,
  KrewIdManageTokenRoute: KrewIdManageTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
