/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as RoomRouteImport } from './routes/room'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminOpportunitiesRouteImport } from './routes/admin.opportunities'
import { Route as AmbassadorsIndexRouteImport } from './routes/ambassadors.index'
import { Route as AmbassadorsIdRouteImport } from './routes/ambassadors.$id'
import { Route as BuildersIndexRouteImport } from './routes/builders.index'
import { Route as BuildersIdRouteImport } from './routes/builders.$id'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as OpportunitiesIdRouteImport } from './routes/opportunities.$id'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as AdminEventsNewRouteImport } from './routes/admin.events.new'
import { Route as AdminOpportunitiesNewRouteImport } from './routes/admin.opportunities.new'
import { Route as AdminEventsIdEditRouteImport } from './routes/admin.events.$id.edit'
import { Route as AdminOpportunitiesIdEditRouteImport } from './routes/admin.opportunities.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomRoute = RoomRouteImport.update({
  id: '/room',
  path: '/room',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesRoute = AdminOpportunitiesRouteImport.update({
  id: '/admin/opportunities',
  path: '/admin/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsIndexRoute = AmbassadorsIndexRouteImport.update({
  id: '/ambassadors/',
  path: '/ambassadors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AmbassadorsIdRoute = AmbassadorsIdRouteImport.update({
  id: '/ambassadors/$id',
  path: '/ambassadors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIndexRoute = BuildersIndexRouteImport.update({
  id: '/builders/',
  path: '/builders/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersIdRoute = BuildersIdRouteImport.update({
  id: '/builders/$id',
  path: '/builders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIdRoute = OpportunitiesIdRouteImport.update({
  id: '/opportunities/$id',
  path: '/opportunities/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminOpportunitiesNewRoute = AdminOpportunitiesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOpportunitiesRoute,
} as any)
const AdminEventsIdEditRoute = AdminEventsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AdminEventsRoute,
} as any)
const AdminOpportunitiesIdEditRoute =
  AdminOpportunitiesIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => AdminOpportunitiesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ambassadors/': typeof AmbassadorsIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin': typeof AdminIndexRoute
  '/ambassadors': typeof AmbassadorsIndexRoute
  '/builders': typeof BuildersIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/guidelines': typeof GuidelinesRoute
  '/room': typeof RoomRoute
  '/saved': typeof SavedRoute
  '/submit': typeof SubmitRoute
  '/admin/events': typeof AdminEventsRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/opportunities': typeof AdminOpportunitiesRouteWithChildren
  '/ambassadors/$id': typeof AmbassadorsIdRoute
  '/builders/$id': typeof BuildersIdRoute
  '/opportunities/$id': typeof OpportunitiesIdRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ambassadors/': typeof AmbassadorsIndexRoute
  '/builders/': typeof BuildersIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/events/$id/edit': typeof AdminEventsIdEditRoute
  '/admin/opportunities/$id/edit': typeof AdminOpportunitiesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/guidelines'
    | '/room'
    | '/saved'
    | '/submit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/opportunities/$id'
    | '/projects/$id'
    | '/admin/'
    | '/ambassadors/'
    | '/builders/'
    | '/opportunities/'
    | '/projects/'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/guidelines'
    | '/room'
    | '/saved'
    | '/submit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/opportunities/$id'
    | '/projects/$id'
    | '/admin'
    | '/ambassadors'
    | '/builders'
    | '/opportunities'
    | '/projects'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/guidelines'
    | '/room'
    | '/saved'
    | '/submit'
    | '/admin/events'
    | '/admin/login'
    | '/admin/opportunities'
    | '/ambassadors/$id'
    | '/builders/$id'
    | '/opportunities/$id'
    | '/projects/$id'
    | '/admin/'
    | '/ambassadors/'
    | '/builders/'
    | '/opportunities/'
    | '/projects/'
    | '/admin/events/new'
    | '/admin/opportunities/new'
    | '/admin/events/$id/edit'
    | '/admin/opportunities/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  GuidelinesRoute: typeof GuidelinesRoute
  RoomRoute: typeof RoomRoute
  SavedRoute: typeof SavedRoute
  SubmitRoute: typeof SubmitRoute
  AdminEventsRoute: typeof AdminEventsRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOpportunitiesRoute: typeof AdminOpportunitiesRouteWithChildren
  AmbassadorsIdRoute: typeof AmbassadorsIdRoute
  BuildersIdRoute: typeof BuildersIdRoute
  OpportunitiesIdRoute: typeof OpportunitiesIdRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AmbassadorsIndexRoute: typeof AmbassadorsIndexRoute
  BuildersIndexRoute: typeof BuildersIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room': {
      id: '/room'
      path: '/room'
      fullPath: '/room'
      preLoaderRoute: typeof RoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities': {
      id: '/admin/opportunities'
      path: '/admin/opportunities'
      fullPath: '/admin/opportunities'
      preLoaderRoute: typeof AdminOpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors/': {
      id: '/ambassadors/'
      path: '/ambassadors'
      fullPath: '/ambassadors/'
      preLoaderRoute: typeof AmbassadorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ambassadors/$id': {
      id: '/ambassadors/$id'
      path: '/ambassadors/$id'
      fullPath: '/ambassadors/$id'
      preLoaderRoute: typeof AmbassadorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/': {
      id: '/builders/'
      path: '/builders'
      fullPath: '/builders/'
      preLoaderRoute: typeof BuildersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders/$id': {
      id: '/builders/$id'
      path: '/builders/$id'
      fullPath: '/builders/$id'
      preLoaderRoute: typeof BuildersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/$id': {
      id: '/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/opportunities/$id'
      preLoaderRoute: typeof OpportunitiesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/opportunities/new': {
      id: '/admin/opportunities/new'
      path: '/new'
      fullPath: '/admin/opportunities/new'
      preLoaderRoute: typeof AdminOpportunitiesNewRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
    '/admin/events/$id/edit': {
      id: '/admin/events/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/events/$id/edit'
      preLoaderRoute: typeof AdminEventsIdEditRouteImport
      parentRoute: typeof AdminEventsRoute
    }
    '/admin/opportunities/$id/edit': {
      id: '/admin/opportunities/$id/edit'
      path: '/$id/edit'
      fullPath: '/admin/opportunities/$id/edit'
      preLoaderRoute: typeof AdminOpportunitiesIdEditRouteImport
      parentRoute: typeof AdminOpportunitiesRoute
    }
  }
}

interface AdminEventsRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIdEditRoute: typeof AdminEventsIdEditRoute
}

const AdminEventsRouteChildren: AdminEventsRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIdEditRoute: AdminEventsIdEditRoute,
}

const AdminEventsRouteWithChildren = AdminEventsRoute._addFileChildren(
  AdminEventsRouteChildren,
)

interface AdminOpportunitiesRouteChildren {
  AdminOpportunitiesNewRoute: typeof AdminOpportunitiesNewRoute
  AdminOpportunitiesIdEditRoute: typeof AdminOpportunitiesIdEditRoute
}

const AdminOpportunitiesRouteChildren: AdminOpportunitiesRouteChildren = {
  AdminOpportunitiesNewRoute: AdminOpportunitiesNewRoute,
  AdminOpportunitiesIdEditRoute: AdminOpportunitiesIdEditRoute,
}

const AdminOpportunitiesRouteWithChildren =
  AdminOpportunitiesRoute._addFileChildren(AdminOpportunitiesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  GuidelinesRoute: GuidelinesRoute,
  RoomRoute: RoomRoute,
  SavedRoute: SavedRoute,
  SubmitRoute: SubmitRoute,
  AdminEventsRoute: AdminEventsRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminOpportunitiesRoute: AdminOpportunitiesRouteWithChildren,
  AmbassadorsIdRoute: AmbassadorsIdRoute,
  BuildersIdRoute: BuildersIdRoute,
  OpportunitiesIdRoute: OpportunitiesIdRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AmbassadorsIndexRoute: AmbassadorsIndexRoute,
  BuildersIndexRoute: BuildersIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
